package net.frapontillo.uni.db2.project.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import net.frapontillo.uni.db2.project.db.DipendenteDB;
import net.frapontillo.uni.db2.project.db.DipendenzaDB;
import net.frapontillo.uni.db2.project.db.StrutturaDB;
import net.frapontillo.uni.db2.project.db.TipoAttivitaDB;

/**
 * Class _AttivitaDB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AttivitaDB extends CayenneDataObject {

    public static final String CODICE_PROPERTY = "codice";
    public static final String FRANCHISING_PROPERTY = "franchising";
    public static final String NOME_PROPERTY = "nome";
    public static final String NUM_DIP_PROPERTY = "numDip";
    public static final String PIANO_PROPERTY = "piano";
    public static final String PIVA_PROPERTY = "piva";
    public static final String DIPENDENZAS_PROPERTY = "dipendenzas";
    public static final String TO_DIPENDENTE_PROPERTY = "toDipendente";
    public static final String TO_STRUTTURA_PROPERTY = "toStruttura";
    public static final String TO_TIPO_ATTIVITA_PROPERTY = "toTipoAttivita";

    public static final String ID_ATTIVITA_PK_COLUMN = "id_attivita";

    public void setCodice(String codice) {
        writeProperty("codice", codice);
    }
    public String getCodice() {
        return (String)readProperty("codice");
    }

    public void setFranchising(Boolean franchising) {
        writeProperty("franchising", franchising);
    }
    public Boolean getFranchising() {
        return (Boolean)readProperty("franchising");
    }

    public void setNome(String nome) {
        writeProperty("nome", nome);
    }
    public String getNome() {
        return (String)readProperty("nome");
    }

    public void setNumDip(Integer numDip) {
        writeProperty("numDip", numDip);
    }
    public Integer getNumDip() {
        return (Integer)readProperty("numDip");
    }

    public void setPiano(Integer piano) {
        writeProperty("piano", piano);
    }
    public Integer getPiano() {
        return (Integer)readProperty("piano");
    }

    public void setPiva(String piva) {
        writeProperty("piva", piva);
    }
    public String getPiva() {
        return (String)readProperty("piva");
    }

    public void addToDipendenzas(DipendenzaDB obj) {
        addToManyTarget("dipendenzas", obj, true);
    }
    public void removeFromDipendenzas(DipendenzaDB obj) {
        removeToManyTarget("dipendenzas", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DipendenzaDB> getDipendenzas() {
        return (List<DipendenzaDB>)readProperty("dipendenzas");
    }


    public void setToDipendente(DipendenteDB toDipendente) {
        setToOneTarget("toDipendente", toDipendente, true);
    }

    public DipendenteDB getToDipendente() {
        return (DipendenteDB)readProperty("toDipendente");
    }


    public void setToStruttura(StrutturaDB toStruttura) {
        setToOneTarget("toStruttura", toStruttura, true);
    }

    public StrutturaDB getToStruttura() {
        return (StrutturaDB)readProperty("toStruttura");
    }


    public void setToTipoAttivita(TipoAttivitaDB toTipoAttivita) {
        setToOneTarget("toTipoAttivita", toTipoAttivita, true);
    }

    public TipoAttivitaDB getToTipoAttivita() {
        return (TipoAttivitaDB)readProperty("toTipoAttivita");
    }


}
