package net.frapontillo.uni.db2.project.db.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import net.frapontillo.uni.db2.project.db.AttivitaDB;
import net.frapontillo.uni.db2.project.db.DipendenteDB;

/**
 * Class _DipendenzaDB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DipendenzaDB extends CayenneDataObject {

    public static final String DATA_LICENZIAMENTO_PROPERTY = "dataLicenziamento";
    public static final String TO_ATTIVITA_PROPERTY = "toAttivita";
    public static final String TO_DIPENDENTE_PROPERTY = "toDipendente";

    public static final String CF_DIPENDENTE_PK_COLUMN = "cf_dipendente";
    public static final String DATA_ASSUNZIONE_PK_COLUMN = "data_assunzione";
    public static final String ID_ATTIVITA_PK_COLUMN = "id_attivita";

    public void setDataLicenziamento(Date dataLicenziamento) {
        writeProperty("dataLicenziamento", dataLicenziamento);
    }
    public Date getDataLicenziamento() {
        return (Date)readProperty("dataLicenziamento");
    }

    public void setToAttivita(AttivitaDB toAttivita) {
        setToOneTarget("toAttivita", toAttivita, true);
    }

    public AttivitaDB getToAttivita() {
        return (AttivitaDB)readProperty("toAttivita");
    }


    public void setToDipendente(DipendenteDB toDipendente) {
        setToOneTarget("toDipendente", toDipendente, true);
    }

    public DipendenteDB getToDipendente() {
        return (DipendenteDB)readProperty("toDipendente");
    }


}
