package net.frapontillo.uni.db2.project.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import net.frapontillo.uni.db2.project.db.StrutturaDB;

/**
 * Class _TipoStrutturaDB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoStrutturaDB extends CayenneDataObject {

    public static final String CODICE_PROPERTY = "codice";
    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String STRUTTURAS_PROPERTY = "strutturas";

    public static final String ID_PK_COLUMN = "id";

    public void setCodice(String codice) {
        writeProperty("codice", codice);
    }
    public String getCodice() {
        return (String)readProperty("codice");
    }

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void addToStrutturas(StrutturaDB obj) {
        addToManyTarget("strutturas", obj, true);
    }
    public void removeFromStrutturas(StrutturaDB obj) {
        removeToManyTarget("strutturas", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<StrutturaDB> getStrutturas() {
        return (List<StrutturaDB>)readProperty("strutturas");
    }


}
