package net.frapontillo.uni.db2.project.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import net.frapontillo.uni.db2.project.db.AttivitaDB;

/**
 * Class _TipoAttivitaDB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoAttivitaDB extends CayenneDataObject {

    public static final String DESCRIZIONE_PROPERTY = "descrizione";
    public static final String ATTIVITAS_PROPERTY = "attivitas";

    public static final String ID_PK_COLUMN = "id";

    public void setDescrizione(String descrizione) {
        writeProperty("descrizione", descrizione);
    }
    public String getDescrizione() {
        return (String)readProperty("descrizione");
    }

    public void addToAttivitas(AttivitaDB obj) {
        addToManyTarget("attivitas", obj, true);
    }
    public void removeFromAttivitas(AttivitaDB obj) {
        removeToManyTarget("attivitas", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AttivitaDB> getAttivitas() {
        return (List<AttivitaDB>)readProperty("attivitas");
    }


}
