package net.frapontillo.uni.db2.project.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import net.frapontillo.uni.db2.project.db.UserSessionDB;

/**
 * Class _UserDB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserDB extends CayenneDataObject {

    public static final String PASSWORD_PROPERTY = "password";
    public static final String USERNAME_PROPERTY = "username";
    public static final String USER_SESSIONS_PROPERTY = "userSessions";

    public static final String ID_PK_COLUMN = "id";

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void addToUserSessions(UserSessionDB obj) {
        addToManyTarget("userSessions", obj, true);
    }
    public void removeFromUserSessions(UserSessionDB obj) {
        removeToManyTarget("userSessions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UserSessionDB> getUserSessions() {
        return (List<UserSessionDB>)readProperty("userSessions");
    }


}
