package net.frapontillo.uni.db2.project.db.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import net.frapontillo.uni.db2.project.db.UserDB;

/**
 * Class _UserSessionDB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserSessionDB extends CayenneDataObject {

    public static final String AUTHCODE_PROPERTY = "authcode";
    public static final String DATE_LOGIN_PROPERTY = "dateLogin";
    public static final String DATE_LOGOUT_PROPERTY = "dateLogout";
    public static final String TO_USER_PROPERTY = "toUser";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthcode(String authcode) {
        writeProperty("authcode", authcode);
    }
    public String getAuthcode() {
        return (String)readProperty("authcode");
    }

    public void setDateLogin(Date dateLogin) {
        writeProperty("dateLogin", dateLogin);
    }
    public Date getDateLogin() {
        return (Date)readProperty("dateLogin");
    }

    public void setDateLogout(Date dateLogout) {
        writeProperty("dateLogout", dateLogout);
    }
    public Date getDateLogout() {
        return (Date)readProperty("dateLogout");
    }

    public void setToUser(UserDB toUser) {
        setToOneTarget("toUser", toUser, true);
    }

    public UserDB getToUser() {
        return (UserDB)readProperty("toUser");
    }


}
