/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class AttivitaDB extends org.jooq.impl.UpdatableTableImpl<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB> {

	private static final long serialVersionUID = -1133004281;

	/**
	 * The singleton instance of public.attivita
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB ATTIVITA = new net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB> getRecordType() {
		return net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB.class;
	}

	/**
	 * The table column <code>public.attivita.id_attivita</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.Integer> ID_ATTIVITA = createField("id_attivita", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.attivita.nome</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.attivita.num_dip</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.Integer> NUM_DIP = createField("num_dip", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.attivita.piva</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.String> PIVA = createField("piva", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.attivita.codice</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.String> CODICE = createField("codice", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.attivita.franchising</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.Boolean> FRANCHISING = createField("franchising", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * The table column <code>public.attivita.id_struttura</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT attivita__fk_attivita_struttura
	 * FOREIGN KEY (id_struttura)
	 * REFERENCES public.struttura (id_struttura)
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.Integer> ID_STRUTTURA = createField("id_struttura", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.attivita.piano</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.Integer> PIANO = createField("piano", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.attivita.id_tipo_attivita</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT attivita__fk_attivita_tipo_attivita
	 * FOREIGN KEY (id_tipo_attivita)
	 * REFERENCES public.tipo_attivita (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.Integer> ID_TIPO_ATTIVITA = createField("id_tipo_attivita", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.attivita.cf_dipendente_manager</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT attivita__fk_attivita_dipendente_manager
	 * FOREIGN KEY (cf_dipendente_manager)
	 * REFERENCES public.dipendente (cf)
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.String> CF_DIPENDENTE_MANAGER = createField("cf_dipendente_manager", org.jooq.impl.SQLDataType.VARCHAR, this);

	public AttivitaDB() {
		super("attivita", net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC);
	}

	public AttivitaDB(java.lang.String alias) {
		super(alias, net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC, net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA);
	}

	@Override
	public org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, java.lang.Integer> getIdentity() {
		return net.frapontillo.uni.db2.project.jooq.Keys.IDENTITY_ATTIVITA;
	}

	@Override
	public org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB> getMainKey() {
		return net.frapontillo.uni.db2.project.jooq.Keys.PK_ATTIVITA;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB>>asList(net.frapontillo.uni.db2.project.jooq.Keys.PK_ATTIVITA);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, ?>>asList(net.frapontillo.uni.db2.project.jooq.Keys.ATTIVITA__FK_ATTIVITA_STRUTTURA, net.frapontillo.uni.db2.project.jooq.Keys.ATTIVITA__FK_ATTIVITA_TIPO_ATTIVITA, net.frapontillo.uni.db2.project.jooq.Keys.ATTIVITA__FK_ATTIVITA_DIPENDENTE_MANAGER);
	}

	@Override
	public net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB as(java.lang.String alias) {
		return new net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB(alias);
	}
}
