/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Dipendenza extends org.jooq.impl.UpdatableTableImpl<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord> {

	private static final long serialVersionUID = 979413091;

	/**
	 * The singleton instance of public.dipendenza
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.Dipendenza DIPENDENZA = new net.frapontillo.uni.db2.project.jooq.tables.Dipendenza();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord> getRecordType() {
		return net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord.class;
	}

	/**
	 * The table column <code>public.dipendenza.cf_dipendente</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_dipendente
	 * FOREIGN KEY (cf_dipendente)
	 * REFERENCES public.dipendente (cf)
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, java.lang.String> CF_DIPENDENTE = createField("cf_dipendente", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.dipendenza.id_attivita</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_attivita
	 * FOREIGN KEY (id_attivita)
	 * REFERENCES public.attivita (id_attivita)
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, java.lang.Integer> ID_ATTIVITA = createField("id_attivita", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.dipendenza.data_assunzione</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, java.sql.Date> DATA_ASSUNZIONE = createField("data_assunzione", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The table column <code>public.dipendenza.data_licenziamento</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, java.sql.Date> DATA_LICENZIAMENTO = createField("data_licenziamento", org.jooq.impl.SQLDataType.DATE, this);

	public Dipendenza() {
		super("dipendenza", net.frapontillo.uni.db2.project.jooq.Public.PUBLIC);
	}

	public Dipendenza(java.lang.String alias) {
		super(alias, net.frapontillo.uni.db2.project.jooq.Public.PUBLIC, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA);
	}

	@Override
	public org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord> getMainKey() {
		return net.frapontillo.uni.db2.project.jooq.Keys.PK_DIPENDENZA;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord>>asList(net.frapontillo.uni.db2.project.jooq.Keys.PK_DIPENDENZA);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, ?>>asList(net.frapontillo.uni.db2.project.jooq.Keys.DIPENDENZA__FK_DIPENDENZA_DIPENDENTE, net.frapontillo.uni.db2.project.jooq.Keys.DIPENDENZA__FK_DIPENDENZA_ATTIVITA);
	}

	@Override
	public net.frapontillo.uni.db2.project.jooq.tables.Dipendenza as(java.lang.String alias) {
		return new net.frapontillo.uni.db2.project.jooq.tables.Dipendenza(alias);
	}
}
