/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Struttura extends org.jooq.impl.UpdatableTableImpl<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> {

	private static final long serialVersionUID = -1973246705;

	/**
	 * The singleton instance of public.struttura
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.Struttura STRUTTURA = new net.frapontillo.uni.db2.project.jooq.tables.Struttura();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> getRecordType() {
		return net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord.class;
	}

	/**
	 * The table column <code>public.struttura.id_struttura</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, java.lang.Integer> ID_STRUTTURA = createField("id_struttura", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.struttura.codice</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, java.lang.String> CODICE = createField("codice", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.struttura.id_tipo_struttura</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT struttura__fk_struttura_tipo_struttura
	 * FOREIGN KEY (id_tipo_struttura)
	 * REFERENCES public.tipo_struttura (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, java.lang.Integer> ID_TIPO_STRUTTURA = createField("id_tipo_struttura", org.jooq.impl.SQLDataType.INTEGER, this);

	public Struttura() {
		super("struttura", net.frapontillo.uni.db2.project.jooq.Public.PUBLIC);
	}

	public Struttura(java.lang.String alias) {
		super(alias, net.frapontillo.uni.db2.project.jooq.Public.PUBLIC, net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA);
	}

	@Override
	public org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, java.lang.Integer> getIdentity() {
		return net.frapontillo.uni.db2.project.jooq.Keys.IDENTITY_STRUTTURA;
	}

	@Override
	public org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> getMainKey() {
		return net.frapontillo.uni.db2.project.jooq.Keys.PK_STRUTTURA;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord>>asList(net.frapontillo.uni.db2.project.jooq.Keys.PK_STRUTTURA, net.frapontillo.uni.db2.project.jooq.Keys.CN_STRUTTURA_UNIQUE);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, ?>>asList(net.frapontillo.uni.db2.project.jooq.Keys.STRUTTURA__FK_STRUTTURA_TIPO_STRUTTURA);
	}

	@Override
	public net.frapontillo.uni.db2.project.jooq.tables.Struttura as(java.lang.String alias) {
		return new net.frapontillo.uni.db2.project.jooq.tables.Struttura(alias);
	}
}
