/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TipoAttivitaDB extends org.jooq.impl.UpdatableTableImpl<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB> {

	private static final long serialVersionUID = 659241303;

	/**
	 * The singleton instance of public.tipo_attivita
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB TIPO_ATTIVITA = new net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB> getRecordType() {
		return net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB.class;
	}

	/**
	 * The table column <code>public.tipo_attivita.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.tipo_attivita.descrizione</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB, java.lang.String> DESCRIZIONE = createField("descrizione", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TipoAttivitaDB() {
		super("tipo_attivita", net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC);
	}

	public TipoAttivitaDB(java.lang.String alias) {
		super(alias, net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC, net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA);
	}

	@Override
	public org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB, java.lang.Integer> getIdentity() {
		return net.frapontillo.uni.db2.project.jooq.Keys.IDENTITY_TIPO_ATTIVITA;
	}

	@Override
	public org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB> getMainKey() {
		return net.frapontillo.uni.db2.project.jooq.Keys.PK_TIPO_ATTIVITA;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB>>asList(net.frapontillo.uni.db2.project.jooq.Keys.PK_TIPO_ATTIVITA);
	}

	@Override
	public net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB as(java.lang.String alias) {
		return new net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB(alias);
	}
}
