/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TipoStrutturaDB extends org.jooq.impl.UpdatableTableImpl<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB> {

	private static final long serialVersionUID = 920306696;

	/**
	 * The singleton instance of public.tipo_struttura
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB TIPO_STRUTTURA = new net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB> getRecordType() {
		return net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB.class;
	}

	/**
	 * The table column <code>public.tipo_struttura.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.tipo_struttura.descrizione</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB, java.lang.String> DESCRIZIONE = createField("descrizione", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.tipo_struttura.codice</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB, java.lang.String> CODICE = createField("codice", org.jooq.impl.SQLDataType.CHAR, this);

	public TipoStrutturaDB() {
		super("tipo_struttura", net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC);
	}

	public TipoStrutturaDB(java.lang.String alias) {
		super(alias, net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC, net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA);
	}

	@Override
	public org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB, java.lang.Integer> getIdentity() {
		return net.frapontillo.uni.db2.project.jooq.Keys.IDENTITY_TIPO_STRUTTURA;
	}

	@Override
	public org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB> getMainKey() {
		return net.frapontillo.uni.db2.project.jooq.Keys.PK_TIPO_STRUTTURA;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB>>asList(net.frapontillo.uni.db2.project.jooq.Keys.PK_TIPO_STRUTTURA, net.frapontillo.uni.db2.project.jooq.Keys.CN_TIPO_STRUTTURA_UNIQUE_CODICE);
	}

	@Override
	public net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB as(java.lang.String alias) {
		return new net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB(alias);
	}
}
