/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class UserSessionDB extends org.jooq.impl.UpdatableTableImpl<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB> {

	private static final long serialVersionUID = 424536676;

	/**
	 * The singleton instance of public.user_session
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB USER_SESSION = new net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB> getRecordType() {
		return net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB.class;
	}

	/**
	 * The table column <code>public.user_session.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>public.user_session.id_user</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT user_session__fk_user_session_user
	 * FOREIGN KEY (id_user)
	 * REFERENCES public.user (id)
	 * </pre></code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, java.lang.Integer> ID_USER = createField("id_user", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.user_session.date_login</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, java.sql.Date> DATE_LOGIN = createField("date_login", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The table column <code>public.user_session.date_logout</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, java.sql.Date> DATE_LOGOUT = createField("date_logout", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The table column <code>public.user_session.authcode</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, java.lang.String> AUTHCODE = createField("authcode", org.jooq.impl.SQLDataType.VARCHAR, this);

	public UserSessionDB() {
		super("user_session", net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC);
	}

	public UserSessionDB(java.lang.String alias) {
		super(alias, net.frapontillo.uni.db2.project.jooq.PublicDB.PUBLIC, net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION);
	}

	@Override
	public org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, java.lang.Long> getIdentity() {
		return net.frapontillo.uni.db2.project.jooq.Keys.IDENTITY_USER_SESSION;
	}

	@Override
	public org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB> getMainKey() {
		return net.frapontillo.uni.db2.project.jooq.Keys.PK_USER_SESSION;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB>>asList(net.frapontillo.uni.db2.project.jooq.Keys.PK_USER_SESSION, net.frapontillo.uni.db2.project.jooq.Keys.CN_USER_SESSION_AUTHCODE);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, ?>>asList(net.frapontillo.uni.db2.project.jooq.Keys.USER_SESSION__FK_USER_SESSION_USER);
	}

	@Override
	public net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB as(java.lang.String alias) {
		return new net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB(alias);
	}
}
