/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class User extends org.jooq.impl.UpdatableTableImpl<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = -799820723;

	/**
	 * The singleton instance of public.user
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.User USER = new net.frapontillo.uni.db2.project.jooq.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> getRecordType() {
		return net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord.class;
	}

	/**
	 * The table column <code>public.user.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>public.user.username</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>public.user.password</code>
	 */
	public final org.jooq.TableField<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR, this);

	public User() {
		super("user", net.frapontillo.uni.db2.project.jooq.Public.PUBLIC);
	}

	public User(java.lang.String alias) {
		super(alias, net.frapontillo.uni.db2.project.jooq.Public.PUBLIC, net.frapontillo.uni.db2.project.jooq.tables.User.USER);
	}

	@Override
	public org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord, java.lang.Integer> getIdentity() {
		return net.frapontillo.uni.db2.project.jooq.Keys.IDENTITY_USER;
	}

	@Override
	public org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> getMainKey() {
		return net.frapontillo.uni.db2.project.jooq.Keys.PK_USER;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord>>asList(net.frapontillo.uni.db2.project.jooq.Keys.PK_USER, net.frapontillo.uni.db2.project.jooq.Keys.CN_USER_USERNAME);
	}

	@Override
	public net.frapontillo.uni.db2.project.jooq.tables.User as(java.lang.String alias) {
		return new net.frapontillo.uni.db2.project.jooq.tables.User(alias);
	}
}
