/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class AttivitaDaoDB extends org.jooq.impl.DAOImpl<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB, net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB, java.lang.Integer> {

	/**
	 * Create a new AttivitaDaoDB without any factory
	 */
	public AttivitaDaoDB() {
		super(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB.class);
	}

	/**
	 * Create a new AttivitaDaoDB with an attached factory
	 */
	public AttivitaDaoDB(org.jooq.impl.Factory factory) {
		super(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB.class, factory);
	}

	@Override
	protected java.lang.Integer getId(net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB object) {
		return object.getIdAttivita();
	}

	/**
	 * Fetch records that have <code>id_attivita IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByIdAttivitaDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.ID_ATTIVITA, values);
	}

	/**
	 * Fetch a unique that has <code>id_attivita = value</code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB fetchOneByIdAttivitaDB(java.lang.Integer value) {
		return fetchOne(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.ID_ATTIVITA, value);
	}

	/**
	 * Fetch records that have <code>nome IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByNomeDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.NOME, values);
	}

	/**
	 * Fetch records that have <code>num_dip IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByNumDipDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.NUM_DIP, values);
	}

	/**
	 * Fetch records that have <code>piva IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByPivaDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.PIVA, values);
	}

	/**
	 * Fetch records that have <code>codice IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByCodiceDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.CODICE, values);
	}

	/**
	 * Fetch records that have <code>franchising IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByFranchisingDB(java.lang.Boolean... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.FRANCHISING, values);
	}

	/**
	 * Fetch records that have <code>id_struttura IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByIdStrutturaDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.ID_STRUTTURA, values);
	}

	/**
	 * Fetch records that have <code>piano IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByPianoDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.PIANO, values);
	}

	/**
	 * Fetch records that have <code>id_tipo_attivita IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByIdTipoAttivitaDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.ID_TIPO_ATTIVITA, values);
	}

	/**
	 * Fetch records that have <code>cf_dipendente_manager IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.AttivitaDB> fetchByCfDipendenteManagerDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.CF_DIPENDENTE_MANAGER, values);
	}
}
