/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class DipendenteDaoDB extends org.jooq.impl.DAOImpl<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecordDB, net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB, java.lang.String> {

	/**
	 * Create a new DipendenteDaoDB without any factory
	 */
	public DipendenteDaoDB() {
		super(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE, net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB.class);
	}

	/**
	 * Create a new DipendenteDaoDB with an attached factory
	 */
	public DipendenteDaoDB(org.jooq.impl.Factory factory) {
		super(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE, net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB.class, factory);
	}

	@Override
	protected java.lang.String getId(net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB object) {
		return object.getCf();
	}

	/**
	 * Fetch records that have <code>cf IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB> fetchByCfDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE.CF, values);
	}

	/**
	 * Fetch a unique that has <code>cf = value</code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB fetchOneByCfDB(java.lang.String value) {
		return fetchOne(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE.CF, value);
	}

	/**
	 * Fetch records that have <code>nome IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB> fetchByNomeDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE.NOME, values);
	}

	/**
	 * Fetch records that have <code>cognome IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB> fetchByCognomeDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE.COGNOME, values);
	}

	/**
	 * Fetch records that have <code>sesso IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB> fetchBySessoDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE.SESSO, values);
	}

	/**
	 * Fetch records that have <code>luogo_nascita IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB> fetchByLuogoNascitaDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE.LUOGO_NASCITA, values);
	}

	/**
	 * Fetch records that have <code>data_nascita IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.DipendenteDB> fetchByDataNascitaDB(java.sql.Date... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE.DATA_NASCITA, values);
	}
}
