/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class StrutturaDaoDB extends org.jooq.impl.DAOImpl<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecordDB, net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB, java.lang.Integer> {

	/**
	 * Create a new StrutturaDaoDB without any factory
	 */
	public StrutturaDaoDB() {
		super(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB.class);
	}

	/**
	 * Create a new StrutturaDaoDB with an attached factory
	 */
	public StrutturaDaoDB(org.jooq.impl.Factory factory) {
		super(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB.class, factory);
	}

	@Override
	protected java.lang.Integer getId(net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB object) {
		return object.getIdStruttura();
	}

	/**
	 * Fetch records that have <code>id_struttura IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB> fetchByIdStrutturaDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA.ID_STRUTTURA, values);
	}

	/**
	 * Fetch a unique that has <code>id_struttura = value</code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB fetchOneByIdStrutturaDB(java.lang.Integer value) {
		return fetchOne(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA.ID_STRUTTURA, value);
	}

	/**
	 * Fetch records that have <code>codice IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB> fetchByCodiceDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA.CODICE, values);
	}

	/**
	 * Fetch records that have <code>id_tipo_struttura IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.StrutturaDB> fetchByIdTipoStrutturaDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA.ID_TIPO_STRUTTURA, values);
	}
}
