/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TipoAttivitaDaoDB extends org.jooq.impl.DAOImpl<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB, net.frapontillo.uni.db2.project.jooq.tables.pojos.TipoAttivitaDB, java.lang.Integer> {

	/**
	 * Create a new TipoAttivitaDaoDB without any factory
	 */
	public TipoAttivitaDaoDB() {
		super(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.pojos.TipoAttivitaDB.class);
	}

	/**
	 * Create a new TipoAttivitaDaoDB with an attached factory
	 */
	public TipoAttivitaDaoDB(org.jooq.impl.Factory factory) {
		super(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.pojos.TipoAttivitaDB.class, factory);
	}

	@Override
	protected java.lang.Integer getId(net.frapontillo.uni.db2.project.jooq.tables.pojos.TipoAttivitaDB object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.TipoAttivitaDB> fetchByIdDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.ID, values);
	}

	/**
	 * Fetch a unique that has <code>id = value</code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.pojos.TipoAttivitaDB fetchOneByIdDB(java.lang.Integer value) {
		return fetchOne(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.ID, value);
	}

	/**
	 * Fetch records that have <code>descrizione IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.TipoAttivitaDB> fetchByDescrizioneDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.DESCRIZIONE, values);
	}
}
