/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class UserSessionDaoDB extends org.jooq.impl.DAOImpl<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecordDB, net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB, java.lang.Long> {

	/**
	 * Create a new UserSessionDaoDB without any factory
	 */
	public UserSessionDaoDB() {
		super(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION, net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB.class);
	}

	/**
	 * Create a new UserSessionDaoDB with an attached factory
	 */
	public UserSessionDaoDB(org.jooq.impl.Factory factory) {
		super(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION, net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB.class, factory);
	}

	@Override
	protected java.lang.Long getId(net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB> fetchByIdDB(java.lang.Long... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION.ID, values);
	}

	/**
	 * Fetch a unique that has <code>id = value</code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB fetchOneByIdDB(java.lang.Long value) {
		return fetchOne(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION.ID, value);
	}

	/**
	 * Fetch records that have <code>id_user IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB> fetchByIdUserDB(java.lang.Integer... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION.ID_USER, values);
	}

	/**
	 * Fetch records that have <code>date_login IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB> fetchByDateLoginDB(java.sql.Date... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION.DATE_LOGIN, values);
	}

	/**
	 * Fetch records that have <code>date_logout IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB> fetchByDateLogoutDB(java.sql.Date... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION.DATE_LOGOUT, values);
	}

	/**
	 * Fetch records that have <code>authcode IN (values)</code>
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB> fetchByAuthcodeDB(java.lang.String... values) {
		return fetch(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION.AUTHCODE, values);
	}

	/**
	 * Fetch a unique that has <code>authcode = value</code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.pojos.UserSessionDB fetchOneByAuthcodeDB(java.lang.String value) {
		return fetchOne(net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION.AUTHCODE, value);
	}
}
