/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Keys {

	// IDENTITY definitions
	public static final org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, java.lang.Integer> IDENTITY_ATTIVITA = Identities0.IDENTITY_ATTIVITA;
	public static final org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, java.lang.Integer> IDENTITY_STRUTTURA = Identities0.IDENTITY_STRUTTURA;
	public static final org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecord, java.lang.Integer> IDENTITY_TIPO_ATTIVITA = Identities0.IDENTITY_TIPO_ATTIVITA;
	public static final org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord, java.lang.Integer> IDENTITY_TIPO_STRUTTURA = Identities0.IDENTITY_TIPO_STRUTTURA;
	public static final org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
	public static final org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord, java.lang.Long> IDENTITY_USER_SESSION = Identities0.IDENTITY_USER_SESSION;

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord> PK_ATTIVITA = UniqueKeys0.PK_ATTIVITA;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord> PK_DIPENDENTE = UniqueKeys0.PK_DIPENDENTE;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord> PK_DIPENDENZA = UniqueKeys0.PK_DIPENDENZA;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> PK_STRUTTURA = UniqueKeys0.PK_STRUTTURA;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> CN_STRUTTURA_UNIQUE = UniqueKeys0.CN_STRUTTURA_UNIQUE;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecord> PK_TIPO_ATTIVITA = UniqueKeys0.PK_TIPO_ATTIVITA;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord> PK_TIPO_STRUTTURA = UniqueKeys0.PK_TIPO_STRUTTURA;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord> CN_TIPO_STRUTTURA_UNIQUE_CODICE = UniqueKeys0.CN_TIPO_STRUTTURA_UNIQUE_CODICE;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> PK_USER = UniqueKeys0.PK_USER;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> CN_USER_USERNAME = UniqueKeys0.CN_USER_USERNAME;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord> PK_USER_SESSION = UniqueKeys0.PK_USER_SESSION;
	public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord> CN_USER_SESSION_AUTHCODE = UniqueKeys0.CN_USER_SESSION_AUTHCODE;

	// FOREIGN KEY definitions
	public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> ATTIVITA__FK_ATTIVITA_STRUTTURA = ForeignKeys0.ATTIVITA__FK_ATTIVITA_STRUTTURA;
	public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecord> ATTIVITA__FK_ATTIVITA_TIPO_ATTIVITA = ForeignKeys0.ATTIVITA__FK_ATTIVITA_TIPO_ATTIVITA;
	public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord> ATTIVITA__FK_ATTIVITA_DIPENDENTE_MANAGER = ForeignKeys0.ATTIVITA__FK_ATTIVITA_DIPENDENTE_MANAGER;
	public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord> DIPENDENZA__FK_DIPENDENZA_DIPENDENTE = ForeignKeys0.DIPENDENZA__FK_DIPENDENZA_DIPENDENTE;
	public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord> DIPENDENZA__FK_DIPENDENZA_ATTIVITA = ForeignKeys0.DIPENDENZA__FK_DIPENDENZA_ATTIVITA;
	public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord> STRUTTURA__FK_STRUTTURA_TIPO_STRUTTURA = ForeignKeys0.STRUTTURA__FK_STRUTTURA_TIPO_STRUTTURA;
	public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord, net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> USER_SESSION__FK_USER_SESSION_USER = ForeignKeys0.USER_SESSION__FK_USER_SESSION_USER;

	/**
	 * No instances
	 */
	private Keys() {}

	@SuppressWarnings("hiding")
	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, java.lang.Integer> IDENTITY_ATTIVITA = createIdentity(net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.ID_ATTIVITA);
		public static org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, java.lang.Integer> IDENTITY_STRUTTURA = createIdentity(net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA.ID_STRUTTURA);
		public static org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecord, java.lang.Integer> IDENTITY_TIPO_ATTIVITA = createIdentity(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivita.TIPO_ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.TipoAttivita.TIPO_ATTIVITA.ID);
		public static org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord, java.lang.Integer> IDENTITY_TIPO_STRUTTURA = createIdentity(net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura.TIPO_STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura.TIPO_STRUTTURA.ID);
		public static org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = createIdentity(net.frapontillo.uni.db2.project.jooq.tables.User.USER, net.frapontillo.uni.db2.project.jooq.tables.User.USER.ID);
		public static org.jooq.Identity<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord, java.lang.Long> IDENTITY_USER_SESSION = createIdentity(net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION, net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION.ID);
	}

	@SuppressWarnings({"hiding", "unchecked"})
	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord> PK_ATTIVITA = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.ID_ATTIVITA);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord> PK_DIPENDENTE = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE, net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.CF);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord> PK_DIPENDENZA = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.ID_ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.DATA_ASSUNZIONE);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> PK_STRUTTURA = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA.ID_STRUTTURA);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> CN_STRUTTURA_UNIQUE = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA.CODICE, net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA.ID_TIPO_STRUTTURA);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecord> PK_TIPO_ATTIVITA = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivita.TIPO_ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.TipoAttivita.TIPO_ATTIVITA.ID);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord> PK_TIPO_STRUTTURA = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura.TIPO_STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura.TIPO_STRUTTURA.ID);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord> CN_TIPO_STRUTTURA_UNIQUE_CODICE = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura.TIPO_STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura.TIPO_STRUTTURA.CODICE);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> PK_USER = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.User.USER, net.frapontillo.uni.db2.project.jooq.tables.User.USER.ID);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> CN_USER_USERNAME = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.User.USER, net.frapontillo.uni.db2.project.jooq.tables.User.USER.USERNAME);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord> PK_USER_SESSION = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION, net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION.ID);
		public static final org.jooq.UniqueKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord> CN_USER_SESSION_AUTHCODE = createUniqueKey(net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION, net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION.AUTHCODE);
	}

	@SuppressWarnings({"hiding", "unchecked"})
	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord> ATTIVITA__FK_ATTIVITA_STRUTTURA = createForeignKey(net.frapontillo.uni.db2.project.jooq.Keys.PK_STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.ID_STRUTTURA);
		public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecord> ATTIVITA__FK_ATTIVITA_TIPO_ATTIVITA = createForeignKey(net.frapontillo.uni.db2.project.jooq.Keys.PK_TIPO_ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.ID_TIPO_ATTIVITA);
		public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord> ATTIVITA__FK_ATTIVITA_DIPENDENTE_MANAGER = createForeignKey(net.frapontillo.uni.db2.project.jooq.Keys.PK_DIPENDENTE, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.CF_DIPENDENTE_MANAGER);
		public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord> DIPENDENZA__FK_DIPENDENZA_DIPENDENTE = createForeignKey(net.frapontillo.uni.db2.project.jooq.Keys.PK_DIPENDENTE, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE);
		public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord> DIPENDENZA__FK_DIPENDENZA_ATTIVITA = createForeignKey(net.frapontillo.uni.db2.project.jooq.Keys.PK_ATTIVITA, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA, net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.ID_ATTIVITA);
		public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecord, net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecord> STRUTTURA__FK_STRUTTURA_TIPO_STRUTTURA = createForeignKey(net.frapontillo.uni.db2.project.jooq.Keys.PK_TIPO_STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA, net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA.ID_TIPO_STRUTTURA);
		public static final org.jooq.ForeignKey<net.frapontillo.uni.db2.project.jooq.tables.records.UserSessionRecord, net.frapontillo.uni.db2.project.jooq.tables.records.UserRecord> USER_SESSION__FK_USER_SESSION_USER = createForeignKey(net.frapontillo.uni.db2.project.jooq.Keys.PK_USER, net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION, net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION.ID_USER);
	}
}
