/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PublicDB extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -707813284;

	/**
	 * The singleton instance of public
	 */
	public static final PublicDB PUBLIC = new PublicDB();

	/**
	 * No further instances allowed
	 */
	private PublicDB() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			net.frapontillo.uni.db2.project.jooq.Sequences.ATTIVITA_ID_ATTIVITA_SEQ,
			net.frapontillo.uni.db2.project.jooq.Sequences.STRUTTURA_ID_STRUTTURA_SEQ,
			net.frapontillo.uni.db2.project.jooq.Sequences.TIPO_ATTIVITA_ID_SEQ,
			net.frapontillo.uni.db2.project.jooq.Sequences.TIPO_STRUTTURA_ID_SEQ,
			net.frapontillo.uni.db2.project.jooq.Sequences.USER_ID_SEQ,
			net.frapontillo.uni.db2.project.jooq.Sequences.USER_SESSION_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA,
			net.frapontillo.uni.db2.project.jooq.tables.DipendenteDB.DIPENDENTE,
			net.frapontillo.uni.db2.project.jooq.tables.DipendenzaDB.DIPENDENZA,
			net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA,
			net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA,
			net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA,
			net.frapontillo.uni.db2.project.jooq.tables.UserDB.USER,
			net.frapontillo.uni.db2.project.jooq.tables.UserSessionDB.USER_SESSION);
	}
}
