/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all stored procedures and functions in public
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Routines {

	/**
	 * Call public.cerca_dipendente
	 *
	 * @param nomecognome
	 * @throws org.jooq.exception.DataAccessException if something went wrong executing the query
	 */
	public static java.lang.Object cercaDipendente(org.jooq.Configuration configuration, java.lang.String nomecognome) {
		net.frapontillo.uni.db2.project.jooq.routines.CercaDipendente f = new net.frapontillo.uni.db2.project.jooq.routines.CercaDipendente();
		f.setNomecognome(nomecognome);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get public.cerca_dipendente as a field
	 *
	 * @param nomecognome
	 */
	public static org.jooq.Field<java.lang.Object> cercaDipendente(java.lang.String nomecognome) {
		net.frapontillo.uni.db2.project.jooq.routines.CercaDipendente f = new net.frapontillo.uni.db2.project.jooq.routines.CercaDipendente();
		f.setNomecognome(nomecognome);

		return f.asField();
	}

	/**
	 * Get public.cerca_dipendente as a field
	 *
	 * @param nomecognome
	 */
	public static org.jooq.Field<java.lang.Object> cercaDipendente(org.jooq.Field<java.lang.String> nomecognome) {
		net.frapontillo.uni.db2.project.jooq.routines.CercaDipendente f = new net.frapontillo.uni.db2.project.jooq.routines.CercaDipendente();
		f.setNomecognome(nomecognome);

		return f.asField();
	}

	/**
	 * Call public.del_dipendenza
	 *
	 * @throws org.jooq.exception.DataAccessException if something went wrong executing the query
	 */
	public static java.lang.Object delDipendenza(org.jooq.Configuration configuration) {
		net.frapontillo.uni.db2.project.jooq.routines.DelDipendenza f = new net.frapontillo.uni.db2.project.jooq.routines.DelDipendenza();

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get public.del_dipendenza as a field
	 *
	 */
	public static org.jooq.Field<java.lang.Object> delDipendenza() {
		net.frapontillo.uni.db2.project.jooq.routines.DelDipendenza f = new net.frapontillo.uni.db2.project.jooq.routines.DelDipendenza();

		return f.asField();
	}

	/**
	 * Call public.esiste_sessione
	 *
	 * @param auth
	 * @throws org.jooq.exception.DataAccessException if something went wrong executing the query
	 */
	public static java.lang.Boolean esisteSessione(org.jooq.Configuration configuration, java.lang.String auth) {
		net.frapontillo.uni.db2.project.jooq.routines.EsisteSessione f = new net.frapontillo.uni.db2.project.jooq.routines.EsisteSessione();
		f.setAuth(auth);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get public.esiste_sessione as a field
	 *
	 * @param auth
	 */
	public static org.jooq.Field<java.lang.Boolean> esisteSessione(java.lang.String auth) {
		net.frapontillo.uni.db2.project.jooq.routines.EsisteSessione f = new net.frapontillo.uni.db2.project.jooq.routines.EsisteSessione();
		f.setAuth(auth);

		return f.asField();
	}

	/**
	 * Get public.esiste_sessione as a field
	 *
	 * @param auth
	 */
	public static org.jooq.Field<java.lang.Boolean> esisteSessione(org.jooq.Field<java.lang.String> auth) {
		net.frapontillo.uni.db2.project.jooq.routines.EsisteSessione f = new net.frapontillo.uni.db2.project.jooq.routines.EsisteSessione();
		f.setAuth(auth);

		return f.asField();
	}

	/**
	 * Call public.ins_dipendenza
	 *
	 * @throws org.jooq.exception.DataAccessException if something went wrong executing the query
	 */
	public static java.lang.Object insDipendenza(org.jooq.Configuration configuration) {
		net.frapontillo.uni.db2.project.jooq.routines.InsDipendenza f = new net.frapontillo.uni.db2.project.jooq.routines.InsDipendenza();

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get public.ins_dipendenza as a field
	 *
	 */
	public static org.jooq.Field<java.lang.Object> insDipendenza() {
		net.frapontillo.uni.db2.project.jooq.routines.InsDipendenza f = new net.frapontillo.uni.db2.project.jooq.routines.InsDipendenza();

		return f.asField();
	}

	/**
	 * Call public.upd_dipendenza
	 *
	 * @throws org.jooq.exception.DataAccessException if something went wrong executing the query
	 */
	public static java.lang.Object updDipendenza(org.jooq.Configuration configuration) {
		net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenza f = new net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenza();

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get public.upd_dipendenza as a field
	 *
	 */
	public static org.jooq.Field<java.lang.Object> updDipendenza() {
		net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenza f = new net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenza();

		return f.asField();
	}

	/**
	 * Call public.upd_dipendenza_licenziamento
	 *
	 * @throws org.jooq.exception.DataAccessException if something went wrong executing the query
	 */
	public static java.lang.Object updDipendenzaLicenziamento(org.jooq.Configuration configuration) {
		net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenzaLicenziamento f = new net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenzaLicenziamento();

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get public.upd_dipendenza_licenziamento as a field
	 *
	 */
	public static org.jooq.Field<java.lang.Object> updDipendenzaLicenziamento() {
		net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenzaLicenziamento f = new net.frapontillo.uni.db2.project.jooq.routines.UpdDipendenzaLicenziamento();

		return f.asField();
	}

	/**
	 * No instances
	 */
	private Routines() {}
}
