/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Tables {

	/**
	 * The table public.attivita
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.Attivita ATTIVITA = net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA;

	/**
	 * The table public.dipendente
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.Dipendente DIPENDENTE = net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE;

	/**
	 * The table public.dipendenza
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.Dipendenza DIPENDENZA = net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA;

	/**
	 * The table public.struttura
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.Struttura STRUTTURA = net.frapontillo.uni.db2.project.jooq.tables.Struttura.STRUTTURA;

	/**
	 * The table public.tipo_attivita
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.TipoAttivita TIPO_ATTIVITA = net.frapontillo.uni.db2.project.jooq.tables.TipoAttivita.TIPO_ATTIVITA;

	/**
	 * The table public.tipo_struttura
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura TIPO_STRUTTURA = net.frapontillo.uni.db2.project.jooq.tables.TipoStruttura.TIPO_STRUTTURA;

	/**
	 * The table public.user
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.User USER = net.frapontillo.uni.db2.project.jooq.tables.User.USER;

	/**
	 * The table public.user_session
	 */
	public static final net.frapontillo.uni.db2.project.jooq.tables.UserSession USER_SESSION = net.frapontillo.uni.db2.project.jooq.tables.UserSession.USER_SESSION;

	/**
	 * No instances
	 */
	private Tables() {}
}
