/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class CercaDipendente extends org.jooq.impl.AbstractRoutine<java.lang.Object> {

	private static final long serialVersionUID = -1023840600;


	/**
	 * The procedure parameter <code>public.cerca_dipendente.RETURN_VALUE</code>
	 * <p>
	 * The SQL type of this item (USER-DEFINED, dipendente) could not be mapped.<br/>
	 * Deserialising this field might not work!
	 */
	public static final org.jooq.Parameter<java.lang.Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.util.postgres.PostgresDataType.getDefaultDataType("USER-DEFINED"));

	/**
	 * The procedure parameter <code>public.cerca_dipendente.nomecognome</code>
	 */
	public static final org.jooq.Parameter<java.lang.String> NOMECOGNOME = createParameter("nomecognome", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * Create a new routine call instance
	 */
	public CercaDipendente() {
		super("cerca_dipendente", net.frapontillo.uni.db2.project.jooq.Public.PUBLIC, org.jooq.util.postgres.PostgresDataType.getDefaultDataType("USER-DEFINED"));

		setReturnParameter(RETURN_VALUE);
		addInParameter(NOMECOGNOME);
	}

	/**
	 * Set the <code>nomecognome</code> parameter IN value to the routine
	 */
	public void setNomecognome(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.routines.CercaDipendente.NOMECOGNOME, value);
	}

	/**
	 * Set the <code>nomecognome</code> parameter to the function
	 * <p>
	 * Use this method only, if the function is called as a {@link org.jooq.Field} in a {@link org.jooq.Select} statement!
	 */
	public void setNomecognome(org.jooq.Field<java.lang.String> field) {
		setField(NOMECOGNOME, field);
	}
}
