/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class DipendenteRecord extends org.jooq.impl.UpdatableRecordImpl<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord> {

	private static final long serialVersionUID = 1881682887;

	/**
	 * The table column <code>public.dipendente.cf</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setCf(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.CF, value);
	}

	/**
	 * The table column <code>public.dipendente.cf</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getCf() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.CF);
	}

	/**
	 * The table column <code>public.dipendente.cf</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord> fetchAttivitaList() {
		return create()
			.selectFrom(net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA)
			.where(net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.CF_DIPENDENTE_MANAGER.equal(getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.CF)))
			.fetch();
	}

	/**
	 * The table column <code>public.dipendente.cf</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord> fetchDipendenzaList() {
		return create()
			.selectFrom(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA)
			.where(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE.equal(getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.CF)))
			.fetch();
	}

	/**
	 * The table column <code>public.dipendente.nome</code>
	 */
	public void setNome(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.NOME, value);
	}

	/**
	 * The table column <code>public.dipendente.nome</code>
	 */
	public java.lang.String getNome() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.NOME);
	}

	/**
	 * The table column <code>public.dipendente.cognome</code>
	 */
	public void setCognome(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.COGNOME, value);
	}

	/**
	 * The table column <code>public.dipendente.cognome</code>
	 */
	public java.lang.String getCognome() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.COGNOME);
	}

	/**
	 * The table column <code>public.dipendente.sesso</code>
	 */
	public void setSesso(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.SESSO, value);
	}

	/**
	 * The table column <code>public.dipendente.sesso</code>
	 */
	public java.lang.String getSesso() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.SESSO);
	}

	/**
	 * The table column <code>public.dipendente.luogo_nascita</code>
	 */
	public void setLuogoNascita(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.LUOGO_NASCITA, value);
	}

	/**
	 * The table column <code>public.dipendente.luogo_nascita</code>
	 */
	public java.lang.String getLuogoNascita() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.LUOGO_NASCITA);
	}

	/**
	 * The table column <code>public.dipendente.data_nascita</code>
	 */
	public void setDataNascita(java.sql.Date value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.DATA_NASCITA, value);
	}

	/**
	 * The table column <code>public.dipendente.data_nascita</code>
	 */
	public java.sql.Date getDataNascita() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.DATA_NASCITA);
	}

	/**
	 * Create a detached DipendenteRecord
	 */
	public DipendenteRecord() {
		super(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE);
	}
}
