/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class DipendenzaRecord extends org.jooq.impl.UpdatableRecordImpl<net.frapontillo.uni.db2.project.jooq.tables.records.DipendenzaRecord> {

	private static final long serialVersionUID = -1801401526;

	/**
	 * The table column <code>public.dipendenza.cf_dipendente</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_dipendente
	 * FOREIGN KEY (cf_dipendente)
	 * REFERENCES public.dipendente (cf)
	 * </pre></code>
	 */
	public void setCfDipendente(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE, value);
	}

	/**
	 * The table column <code>public.dipendenza.cf_dipendente</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_dipendente
	 * FOREIGN KEY (cf_dipendente)
	 * REFERENCES public.dipendente (cf)
	 * </pre></code>
	 */
	public java.lang.String getCfDipendente() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE);
	}

	/**
	 * Link this record to a given {@link net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord 
	 * DipendenteRecord}
	 */
	public void setCfDipendente(net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord value) {
		if (value == null) {
			setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE, null);
		}
		else {
			setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE, value.getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.CF));
		}
	}

	/**
	 * The table column <code>public.dipendenza.cf_dipendente</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_dipendente
	 * FOREIGN KEY (cf_dipendente)
	 * REFERENCES public.dipendente (cf)
	 * </pre></code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.records.DipendenteRecord fetchDipendente() {
		return create()
			.selectFrom(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE)
			.where(net.frapontillo.uni.db2.project.jooq.tables.Dipendente.DIPENDENTE.CF.equal(getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.CF_DIPENDENTE)))
			.fetchOne();
	}

	/**
	 * The table column <code>public.dipendenza.id_attivita</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_attivita
	 * FOREIGN KEY (id_attivita)
	 * REFERENCES public.attivita (id_attivita)
	 * </pre></code>
	 */
	public void setIdAttivita(java.lang.Integer value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.ID_ATTIVITA, value);
	}

	/**
	 * The table column <code>public.dipendenza.id_attivita</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_attivita
	 * FOREIGN KEY (id_attivita)
	 * REFERENCES public.attivita (id_attivita)
	 * </pre></code>
	 */
	public java.lang.Integer getIdAttivita() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.ID_ATTIVITA);
	}

	/**
	 * Link this record to a given {@link net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord 
	 * AttivitaRecord}
	 */
	public void setIdAttivita(net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord value) {
		if (value == null) {
			setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.ID_ATTIVITA, null);
		}
		else {
			setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.ID_ATTIVITA, value.getValue(net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.ID_ATTIVITA));
		}
	}

	/**
	 * The table column <code>public.dipendenza.id_attivita</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT dipendenza__fk_dipendenza_attivita
	 * FOREIGN KEY (id_attivita)
	 * REFERENCES public.attivita (id_attivita)
	 * </pre></code>
	 */
	public net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecord fetchAttivita() {
		return create()
			.selectFrom(net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA)
			.where(net.frapontillo.uni.db2.project.jooq.tables.Attivita.ATTIVITA.ID_ATTIVITA.equal(getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.ID_ATTIVITA)))
			.fetchOne();
	}

	/**
	 * The table column <code>public.dipendenza.data_assunzione</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setDataAssunzione(java.sql.Date value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.DATA_ASSUNZIONE, value);
	}

	/**
	 * The table column <code>public.dipendenza.data_assunzione</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.sql.Date getDataAssunzione() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.DATA_ASSUNZIONE);
	}

	/**
	 * The table column <code>public.dipendenza.data_licenziamento</code>
	 */
	public void setDataLicenziamento(java.sql.Date value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.DATA_LICENZIAMENTO, value);
	}

	/**
	 * The table column <code>public.dipendenza.data_licenziamento</code>
	 */
	public java.sql.Date getDataLicenziamento() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA.DATA_LICENZIAMENTO);
	}

	/**
	 * Create a detached DipendenzaRecord
	 */
	public DipendenzaRecord() {
		super(net.frapontillo.uni.db2.project.jooq.tables.Dipendenza.DIPENDENZA);
	}
}
