/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TipoAttivitaRecordDB extends org.jooq.impl.UpdatableRecordImpl<net.frapontillo.uni.db2.project.jooq.tables.records.TipoAttivitaRecordDB> {

	private static final long serialVersionUID = 373757192;

	/**
	 * The table column <code>public.tipo_attivita.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.ID, value);
	}

	/**
	 * The table column <code>public.tipo_attivita.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.ID);
	}

	/**
	 * The table column <code>public.tipo_attivita.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.records.AttivitaRecordDB> fetchAttivitaDBList() {
		return create()
			.selectFrom(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA)
			.where(net.frapontillo.uni.db2.project.jooq.tables.AttivitaDB.ATTIVITA.ID_TIPO_ATTIVITA.equal(getValue(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.ID)))
			.fetch();
	}

	/**
	 * The table column <code>public.tipo_attivita.descrizione</code>
	 */
	public void setDescrizione(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.DESCRIZIONE, value);
	}

	/**
	 * The table column <code>public.tipo_attivita.descrizione</code>
	 */
	public java.lang.String getDescrizione() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA.DESCRIZIONE);
	}

	/**
	 * Create a detached TipoAttivitaRecordDB
	 */
	public TipoAttivitaRecordDB() {
		super(net.frapontillo.uni.db2.project.jooq.tables.TipoAttivitaDB.TIPO_ATTIVITA);
	}
}
