/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TipoStrutturaRecordDB extends org.jooq.impl.UpdatableRecordImpl<net.frapontillo.uni.db2.project.jooq.tables.records.TipoStrutturaRecordDB> {

	private static final long serialVersionUID = 1898405772;

	/**
	 * The table column <code>public.tipo_struttura.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA.ID, value);
	}

	/**
	 * The table column <code>public.tipo_struttura.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA.ID);
	}

	/**
	 * The table column <code>public.tipo_struttura.id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.util.List<net.frapontillo.uni.db2.project.jooq.tables.records.StrutturaRecordDB> fetchStrutturaDBList() {
		return create()
			.selectFrom(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA)
			.where(net.frapontillo.uni.db2.project.jooq.tables.StrutturaDB.STRUTTURA.ID_TIPO_STRUTTURA.equal(getValue(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA.ID)))
			.fetch();
	}

	/**
	 * The table column <code>public.tipo_struttura.descrizione</code>
	 */
	public void setDescrizione(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA.DESCRIZIONE, value);
	}

	/**
	 * The table column <code>public.tipo_struttura.descrizione</code>
	 */
	public java.lang.String getDescrizione() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA.DESCRIZIONE);
	}

	/**
	 * The table column <code>public.tipo_struttura.codice</code>
	 */
	public void setCodice(java.lang.String value) {
		setValue(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA.CODICE, value);
	}

	/**
	 * The table column <code>public.tipo_struttura.codice</code>
	 */
	public java.lang.String getCodice() {
		return getValue(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA.CODICE);
	}

	/**
	 * Create a detached TipoStrutturaRecordDB
	 */
	public TipoStrutturaRecordDB() {
		super(net.frapontillo.uni.db2.project.jooq.tables.TipoStrutturaDB.TIPO_STRUTTURA);
	}
}
