/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class AttivitaDB implements java.io.Serializable {

	private static final long serialVersionUID = -1936422192;

	private java.lang.Integer idAttivita;
	private java.lang.String  nome;
	private java.lang.Integer numDip;
	private java.lang.String  piva;
	private java.lang.String  codice;
	private java.lang.Boolean franchising;
	private java.lang.Integer idStruttura;
	private java.lang.Integer piano;
	private java.lang.Integer idTipoAttivita;
	private java.lang.String  cfDipendenteManager;

	public java.lang.Integer getIdAttivita() {
		return this.idAttivita;
	}

	public void setIdAttivita(java.lang.Integer idAttivita) {
		this.idAttivita = idAttivita;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.Integer getNumDip() {
		return this.numDip;
	}

	public void setNumDip(java.lang.Integer numDip) {
		this.numDip = numDip;
	}

	public java.lang.String getPiva() {
		return this.piva;
	}

	public void setPiva(java.lang.String piva) {
		this.piva = piva;
	}

	public java.lang.String getCodice() {
		return this.codice;
	}

	public void setCodice(java.lang.String codice) {
		this.codice = codice;
	}

	public java.lang.Boolean getFranchising() {
		return this.franchising;
	}

	public void setFranchising(java.lang.Boolean franchising) {
		this.franchising = franchising;
	}

	public java.lang.Integer getIdStruttura() {
		return this.idStruttura;
	}

	public void setIdStruttura(java.lang.Integer idStruttura) {
		this.idStruttura = idStruttura;
	}

	public java.lang.Integer getPiano() {
		return this.piano;
	}

	public void setPiano(java.lang.Integer piano) {
		this.piano = piano;
	}

	public java.lang.Integer getIdTipoAttivita() {
		return this.idTipoAttivita;
	}

	public void setIdTipoAttivita(java.lang.Integer idTipoAttivita) {
		this.idTipoAttivita = idTipoAttivita;
	}

	public java.lang.String getCfDipendenteManager() {
		return this.cfDipendenteManager;
	}

	public void setCfDipendenteManager(java.lang.String cfDipendenteManager) {
		this.cfDipendenteManager = cfDipendenteManager;
	}
}
