/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class DipendenteDB implements java.io.Serializable {

	private static final long serialVersionUID = -1571375537;

	private java.lang.String cf;
	private java.lang.String nome;
	private java.lang.String cognome;
	private java.lang.String sesso;
	private java.lang.String luogoNascita;
	private java.sql.Date    dataNascita;

	public java.lang.String getCf() {
		return this.cf;
	}

	public void setCf(java.lang.String cf) {
		this.cf = cf;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.String getCognome() {
		return this.cognome;
	}

	public void setCognome(java.lang.String cognome) {
		this.cognome = cognome;
	}

	public java.lang.String getSesso() {
		return this.sesso;
	}

	public void setSesso(java.lang.String sesso) {
		this.sesso = sesso;
	}

	public java.lang.String getLuogoNascita() {
		return this.luogoNascita;
	}

	public void setLuogoNascita(java.lang.String luogoNascita) {
		this.luogoNascita = luogoNascita;
	}

	public java.sql.Date getDataNascita() {
		return this.dataNascita;
	}

	public void setDataNascita(java.sql.Date dataNascita) {
		this.dataNascita = dataNascita;
	}
}
