/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class DipendenzaDB implements java.io.Serializable {

	private static final long serialVersionUID = 334104355;

	private java.lang.String  cfDipendente;
	private java.lang.Integer idAttivita;
	private java.sql.Date     dataAssunzione;
	private java.sql.Date     dataLicenziamento;

	public java.lang.String getCfDipendente() {
		return this.cfDipendente;
	}

	public void setCfDipendente(java.lang.String cfDipendente) {
		this.cfDipendente = cfDipendente;
	}

	public java.lang.Integer getIdAttivita() {
		return this.idAttivita;
	}

	public void setIdAttivita(java.lang.Integer idAttivita) {
		this.idAttivita = idAttivita;
	}

	public java.sql.Date getDataAssunzione() {
		return this.dataAssunzione;
	}

	public void setDataAssunzione(java.sql.Date dataAssunzione) {
		this.dataAssunzione = dataAssunzione;
	}

	public java.sql.Date getDataLicenziamento() {
		return this.dataLicenziamento;
	}

	public void setDataLicenziamento(java.sql.Date dataLicenziamento) {
		this.dataLicenziamento = dataLicenziamento;
	}
}
