/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class StrutturaDB implements java.io.Serializable {

	private static final long serialVersionUID = -216403929;

	private java.lang.Integer idStruttura;
	private java.lang.String  codice;
	private java.lang.Integer idTipoStruttura;

	public java.lang.Integer getIdStruttura() {
		return this.idStruttura;
	}

	public void setIdStruttura(java.lang.Integer idStruttura) {
		this.idStruttura = idStruttura;
	}

	public java.lang.String getCodice() {
		return this.codice;
	}

	public void setCodice(java.lang.String codice) {
		this.codice = codice;
	}

	public java.lang.Integer getIdTipoStruttura() {
		return this.idTipoStruttura;
	}

	public void setIdTipoStruttura(java.lang.Integer idTipoStruttura) {
		this.idTipoStruttura = idTipoStruttura;
	}
}
