/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class TipoStrutturaDB implements java.io.Serializable {

	private static final long serialVersionUID = -120030108;

	private java.lang.Integer id;
	private java.lang.String  descrizione;
	private java.lang.String  codice;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(java.lang.String descrizione) {
		this.descrizione = descrizione;
	}

	public java.lang.String getCodice() {
		return this.codice;
	}

	public void setCodice(java.lang.String codice) {
		this.codice = codice;
	}
}
