/**
 * This class is generated by jOOQ
 */
package net.frapontillo.uni.db2.project.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.2"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class UserSessionDB implements java.io.Serializable {

	private static final long serialVersionUID = -1918165028;

	private java.lang.Long    id;
	private java.lang.Integer idUser;
	private java.sql.Date     dateLogin;
	private java.sql.Date     dateLogout;
	private java.lang.String  authcode;

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(java.lang.Integer idUser) {
		this.idUser = idUser;
	}

	public java.sql.Date getDateLogin() {
		return this.dateLogin;
	}

	public void setDateLogin(java.sql.Date dateLogin) {
		this.dateLogin = dateLogin;
	}

	public java.sql.Date getDateLogout() {
		return this.dateLogout;
	}

	public void setDateLogout(java.sql.Date dateLogout) {
		this.dateLogout = dateLogout;
	}

	public java.lang.String getAuthcode() {
		return this.authcode;
	}

	public void setAuthcode(java.lang.String authcode) {
		this.authcode = authcode;
	}
}
